name = "photobooth-pages"
compatibility_date = "2024-10-01"

[pages]
build_output_dir = "./public"
functions_directory = "./functions"

# KV namespaces for fonts and themes data
[[kv_namespaces]]
binding = "FONTS_KV"
id = "622b021e6ed14205af232416f61b91f8"

[[kv_namespaces]]
binding = "THEMES_KV"
id = "9bf1e03c07b747caa51bf6d6ebac6c35"

# R2 bucket for uploaded assets
[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "photos"
